APP_NAME = "MyApp"
DEV_ENV = "dev"
MODEL_DEPLOYMENT_NAME= "MODEL_DEPLOYMENT_NAME"

# Demo agent constants
DEMO_AGENT_ENDPOINT = "DEMO_AGENT_ENDPOINT"
DEMO_AGENT_ID = "DEMO_AGENT_ID"

# Developed agent constants
DEVELOPED_AGENT_PROJECT_ENDPOINT= "DEVELOPED_AGENT_PROJECT_ENDPOINT"

# Custom function agent constants
CUSTOM_FUNCTION_AGENT_ENDPOINT = "CUSTOM_FUNCTION_AGENT_ENDPOINT"